using System;
using Newtonsoft.Json;
using System.IO;
using Microsoft.Extensions.Options;
using GM.DataAccess.DatabaseRepositories;
using GM.DataAccess.FileDataModel;
using GM.Shared.Configuration;

namespace GM.DataAccess.FileRepositories
{
    // This is a "repository" of "viewable" transcripts. Viewable transcripts are the JSON files generated by the last step in the 
    // processing, the adding of tags. They are named "T4-tagged.json", meaning they completed step 4 of the processing.
 
    public class ViewMeetingRepository : IViewMeetingRepository
    {
        private const string STEP4_BASE_NAME = "T4-tagged";
        private const string EXTENSION = "json";

        private readonly AppSettings _config;
        IMeetingRepository _meetingRepository;

        public ViewMeetingRepository(
            IOptions<AppSettings> config,
            IMeetingRepository meetingRepository
            )
        {
            _config = config.Value;
            _meetingRepository = meetingRepository;
        }

        public MeetingView Get(long meetingId)
        {
            string path = _meetingRepository.GetMeetingFolder(meetingId);

            // Todo-g - Remove later - For development: If the data is not in Datafiles folder, copy it from testdata.
            UseTestData.CopyIfNeeded(path, _config.DatafilesPath, _config.TestfilesPath);

            string latestCopy = Path.Combine(_config.DatafilesPath, path, STEP4_BASE_NAME + "." + EXTENSION);

            if (File.Exists(latestCopy))
            {
                return GetViewMeetingByPath(latestCopy);
            }
            else
            {
                return null;
            }
        }

        private MeetingView GetViewMeetingByPath(string path)
        {
            string meetingString = FileSystem.Readfile(path);
            if (meetingString != null)
            {
                MeetingView meeting = JsonConvert.DeserializeObject<MeetingView>(meetingString);
                return meeting;
            } else
            {
                return null;
            }
        }
    }
}
