// <auto-generated />
using System;
using GM.Infrastructure.InfraCore.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GM.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("GM.Application.AppCore.Entities.GovLocations.GovLocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ParentLocationId")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<string>("WebsiteUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ParentLocationId");

                    b.ToTable("GovLocations");
                });

            modelBuilder.Entity("GM.Application.AppCore.Entities.Govbodies.AppointedOfficial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GovbodyId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("GovbodyId");

                    b.ToTable("AppointedOfficials");
                });

            modelBuilder.Entity("GM.Application.AppCore.Entities.Govbodies.ElectedOfficial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GovbodyId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("GovbodyId");

                    b.ToTable("ElectedOfficials");
                });

            modelBuilder.Entity("GM.Application.AppCore.Entities.Govbodies.Govbody", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LongName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ParentLocationId")
                        .HasColumnType("int");

                    b.Property<string>("RecordingsUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TranscriptsUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ParentLocationId");

                    b.ToTable("Govbodies");
                });

            modelBuilder.Entity("GM.Application.AppCore.Entities.Govbodies.ScheduledMeeting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int?>("GovbodyId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GovbodyId");

                    b.ToTable("ScheduledMeeting");
                });

            modelBuilder.Entity("GM.Application.AppCore.Entities.Meetings.Language", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("GovLocationId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("GovLocationId");

                    b.ToTable("Languages");
                });

            modelBuilder.Entity("GM.Application.AppCore.Entities.Meetings.Meeting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Approved")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("GovbodyId")
                        .HasColumnType("int");

                    b.Property<string>("Language")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Length")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SourceFilename")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SourceType")
                        .HasColumnType("int");

                    b.Property<int>("WorkStatus")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GovbodyId");

                    b.ToTable("Meetings");
                });

            modelBuilder.Entity("GM.Application.AppCore.Entities.Meetings.Section", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("MeetingId")
                        .HasColumnType("bigint");

                    b.Property<int?>("MeetingId1")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Sequence")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MeetingId1");

                    b.ToTable("Sections");
                });

            modelBuilder.Entity("GM.Application.AppCore.Entities.Meetings.Talk", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Sequence")
                        .HasColumnType("int");

                    b.Property<int?>("SpeakerId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("TopicDiscussionId")
                        .HasColumnType("bigint");

                    b.Property<int?>("TopicDiscussionId1")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SpeakerId");

                    b.HasIndex("TopicDiscussionId1");

                    b.ToTable("Talks");
                });

            modelBuilder.Entity("GM.Application.AppCore.Entities.Meetings.TopicDiscussion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("SectionId")
                        .HasColumnType("bigint");

                    b.Property<int?>("SectionId1")
                        .HasColumnType("int");

                    b.Property<int>("Sequence")
                        .HasColumnType("int");

                    b.Property<long?>("TopicId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("SectionId1");

                    b.HasIndex("TopicId");

                    b.ToTable("TopicDiscussions");
                });

            modelBuilder.Entity("GM.Application.AppCore.Entities.Speakers.Speaker", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("MeetingId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Speakers");
                });

            modelBuilder.Entity("GM.Application.AppCore.Entities.Topics.Category", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("TopicId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("TopicId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("GM.Application.AppCore.Entities.Topics.Topic", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("GovbodyId")
                        .HasColumnType("int");

                    b.Property<long>("GovernmentBodyId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("GovbodyId");

                    b.ToTable("Topics");
                });

            modelBuilder.Entity("GM.Application.AppCore.Entities.GovLocations.GovLocation", b =>
                {
                    b.HasOne("GM.Application.AppCore.Entities.GovLocations.GovLocation", "ParentLocation")
                        .WithMany()
                        .HasForeignKey("ParentLocationId");
                });

            modelBuilder.Entity("GM.Application.AppCore.Entities.Govbodies.AppointedOfficial", b =>
                {
                    b.HasOne("GM.Application.AppCore.Entities.Govbodies.Govbody", null)
                        .WithMany("AppointedOfficials")
                        .HasForeignKey("GovbodyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GM.Application.AppCore.Entities.Govbodies.ElectedOfficial", b =>
                {
                    b.HasOne("GM.Application.AppCore.Entities.Govbodies.Govbody", null)
                        .WithMany("ElectedOfficials")
                        .HasForeignKey("GovbodyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GM.Application.AppCore.Entities.Govbodies.Govbody", b =>
                {
                    b.HasOne("GM.Application.AppCore.Entities.GovLocations.GovLocation", "ParentLocation")
                        .WithMany("Govbodies")
                        .HasForeignKey("ParentLocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GM.Application.AppCore.Entities.Govbodies.ScheduledMeeting", b =>
                {
                    b.HasOne("GM.Application.AppCore.Entities.Govbodies.Govbody", null)
                        .WithMany("ScheduledMeetings")
                        .HasForeignKey("GovbodyId");
                });

            modelBuilder.Entity("GM.Application.AppCore.Entities.Meetings.Language", b =>
                {
                    b.HasOne("GM.Application.AppCore.Entities.GovLocations.GovLocation", null)
                        .WithMany("Languages")
                        .HasForeignKey("GovLocationId");
                });

            modelBuilder.Entity("GM.Application.AppCore.Entities.Meetings.Meeting", b =>
                {
                    b.HasOne("GM.Application.AppCore.Entities.Govbodies.Govbody", null)
                        .WithMany("Meetings")
                        .HasForeignKey("GovbodyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GM.Application.AppCore.Entities.Meetings.Section", b =>
                {
                    b.HasOne("GM.Application.AppCore.Entities.Meetings.Meeting", null)
                        .WithMany("Sections")
                        .HasForeignKey("MeetingId1");
                });

            modelBuilder.Entity("GM.Application.AppCore.Entities.Meetings.Talk", b =>
                {
                    b.HasOne("GM.Application.AppCore.Entities.Speakers.Speaker", "Speaker")
                        .WithMany()
                        .HasForeignKey("SpeakerId");

                    b.HasOne("GM.Application.AppCore.Entities.Meetings.TopicDiscussion", null)
                        .WithMany("Talks")
                        .HasForeignKey("TopicDiscussionId1");
                });

            modelBuilder.Entity("GM.Application.AppCore.Entities.Meetings.TopicDiscussion", b =>
                {
                    b.HasOne("GM.Application.AppCore.Entities.Meetings.Section", null)
                        .WithMany("TopicDiscussions")
                        .HasForeignKey("SectionId1");

                    b.HasOne("GM.Application.AppCore.Entities.Topics.Topic", "Topic")
                        .WithMany()
                        .HasForeignKey("TopicId");
                });

            modelBuilder.Entity("GM.Application.AppCore.Entities.Topics.Category", b =>
                {
                    b.HasOne("GM.Application.AppCore.Entities.Topics.Topic", null)
                        .WithMany("Categories")
                        .HasForeignKey("TopicId");
                });

            modelBuilder.Entity("GM.Application.AppCore.Entities.Topics.Topic", b =>
                {
                    b.HasOne("GM.Application.AppCore.Entities.Govbodies.Govbody", null)
                        .WithMany("Topics")
                        .HasForeignKey("GovbodyId");
                });
#pragma warning restore 612, 618
        }
    }
}
