using System;
using Newtonsoft.Json;
using System.IO;
using Microsoft.Extensions.Options;
using GM.DatabaseRepositories;
using GM.FileDataModel;
using GM.Configuration;

namespace GM.FileDataRepositories
{
    // This is a "repository" of "viewable" transcripts. Viewable transcripts are the JSON files generated by the last step in the 
    // processing, the adding of tags. They are named "T4-tagged.json", meaning they completed step 4 of the processing.

    public class ViewMeetingRepository : IViewMeetingRepository
    {
        private const string STEP4_BASE_NAME = "T4-tagged";
        private const string EXTENSION = "json";

        private readonly AppSettings _config;
        private readonly MeetingFolder _meetingFolder;

        public ViewMeetingRepository(
            IOptions<AppSettings> config,
            MeetingFolder meetingFolder
            )
        {
            _config = config.Value;
            _meetingFolder = meetingFolder;
        }

        public MeetingView Get(long meetingId)
        {
            string meetingFolder = _meetingFolder.GetPathFromId(meetingId);

            // Todo-g - Remove later - For development: If the data is not in Datafiles folder, copy it from testdata.
            UseTestData.CopyIfNeeded(meetingFolder, _config.DatafilesPath, _config.TestfilesPath);

            string latestCopy = Path.Combine(_config.DatafilesPath, meetingFolder, STEP4_BASE_NAME + "." + EXTENSION);

            if (File.Exists(latestCopy))
            {
                return GetViewMeetingByPath(latestCopy);
            }
            else
            {
                return null;
            }
        }

        private MeetingView GetViewMeetingByPath(string path)
        {
            string meetingString = FileAccess.Readfile(path);
            if (meetingString != null)
            {
                MeetingView meeting = JsonConvert.DeserializeObject<MeetingView>(meetingString);
                return meeting;
            } else
            {
                return null;
            }
        }
    }
}
