#stage 1
FROM node:16 as node
WORKDIR /app
COPY . .
RUN npm install
RUN npm run build:prod
#stage 2
FROM nginx:alpine
COPY --from=node /app/dist /usr/share/nginx/html
# serve index.html for all deep-link paths
COPY --from=node /app/nginx.conf /etc/nginx/conf.d/
# Remove configuration for serving static content (from /usr/share/nginx/html)
RUN rm /etc/nginx/conf.d/default.conf
# Expose port 80
EXPOSE 80
